name: newproject
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  intl: ^0.19.0
  image_picker: ^1.0.4
  flutter_map: ^6.0.0   
  latlong2: ^0.9.0       
  geolocator: ^10.0.0
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/logo.png
  - assets/images/restaurant_placeholder.png
  - assets/images/default_profile.png

